### ISSUE TITLE
Water missing in ring landscapes

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#102]
![image](https://user-images.githubusercontent.com/1581053/79289327-874bbc00-7efb-11ea-98ea-11e2443065ae.png)

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/79293238-c252ed00-7f05-11ea-9054-40f89bf638cf.png)

**Comment by mlcdev** [comment]
can confirm
