### ISSUE TITLE
Fyros bra goes through body if breasts too small

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#109]
![image](https://user-images.githubusercontent.com/1581053/79294041-c8e26400-7f07-11ea-8748-9a04f9ccc190.png)

**Comment by mlcdev** [comment]
Does this mean nobody ever moved the slider to the left? Unnoticed for 15+ years. Wow.

**Comment by kaetemi** [comment]
I guess. Fixed in next patch.

![image](https://user-images.githubusercontent.com/1581053/79325482-d3baea00-7f43-11ea-8237-6b59f7e35f98.png)
