### ISSUE TITLE
Missing texture for Tree-Bore Crafter in Pyr

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#11]
![screenshot_2019-11-17_008](https://user-images.githubusercontent.com/44550003/69009046-c3312400-0951-11ea-96e3-6f240a01e7b3.jpg)

**Comment by kaetemi** [comment]
Please check client log for any filenames.

**Comment by kaetemi** [comment]
https://github.com/kaetemi/ryzomclassic/issues/67
