### ISSUE TITLE
Scenario Editor menu hard to read in char select

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#117]
![broken_menu](https://user-images.githubusercontent.com/44550003/79396256-c6b9ed00-7f7b-11ea-9e0f-6c642120660c.PNG)

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/97427466-7d742e00-190c-11eb-841c-da8e7b2c634e.png)

these texture files are missing

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/97427643-c4faba00-190c-11eb-9de0-a9e9089aa53b.png)

these work. ok to just swap to these?

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/97428758-5ae31480-190e-11eb-9023-252f9c11ef5f.png)

better imo.
