### ISSUE TITLE
Use old logo for executables

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#122]
The client still uses the "new" rootball atys logo, revert it back to the original (handpixeled to 4 times the size). Attached original and remake.

![ryzom_x4_ver7](https://user-images.githubusercontent.com/44550003/79444775-eb45b180-7fdb-11ea-93a7-e93416d38bd8.png)

[ICO.zip](https://github.com/kaetemi/ryzomclassic/files/4486358/ICO.zip)

**Comment by kaetemi** [comment]
Attached png is cut off on the bottom?

**Comment by mlcdev** [comment]
It is not, original logo also has pixels at the bottom.

![vintage_pixels](https://user-images.githubusercontent.com/44550003/79689951-471c6e80-8258-11ea-9fa4-0ef7bf4391f3.PNG)

![pixels](https://user-images.githubusercontent.com/44550003/79689954-4a175f00-8258-11ea-9081-07187721b235.PNG)
