### ISSUE TITLE
Some Ring landscape is wrong.

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#142]
Appears to be jungle chunks inside a forest map? Other maps maybe affected too.

![image](https://user-images.githubusercontent.com/69606701/90690975-7e347800-e26a-11ea-952c-211a7b71122e.png)

**Comment by kaetemi** [comment]
Possible, yes! Had to reverse generate it from the live, because the R2 zone leveldesign files are lost.

**Comment by Xtarsia** [comment]
"R2 zone leveldesign files are lost." How is WG compiling their version? All ring islands (and more) are accessable on live provided you can teleport there.

All maps can be seen here https://maps.bmsite.net/sample/builder.html

**Comment by kaetemi** [comment]
They're not compiling it. They just have the old copy from server and
client.

**Comment by Xtarsia** [comment]
ah... in true WG fashion then...

**Comment by kaetemi** [comment]
- [ ] Rebuild R2 landscape without trees
- [ ] Write tool to diff IGs, and generate a primitive from the diff
- [ ] Diff IGs, regenerate tree primitives from diff
- [ ] Rebuild R2 landscape with the right trees
