### ISSUE TITLE
Broken textures of the outpost weapons

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#149]
They are supposed to be all shiny and metallic, but the currently broken texture has a very pleasing look to it, almost like it was painted on like a tribal weapon. Add them somehow additionally to the original (correctly textured) ones.

![screenshot_2020-09-07_000](https://user-images.githubusercontent.com/44550003/92408207-12dd1800-f13d-11ea-9f8c-323b24c04bb7.jpg)
![screenshot_2020-09-07_001](https://user-images.githubusercontent.com/44550003/92408216-17093580-f13d-11ea-9d75-6c7c38c794e0.jpg)

**Comment by kaetemi** [comment]
No.

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/119446808-9be6be80-bd61-11eb-86f0-4e975beab3c9.png)

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/119452284-c0926480-bd68-11eb-8da7-f67f4b9c68de.png)

**Comment by kaetemi** [comment]
# Defective Files
* [x] ge_fy_wea_trib_grand_bouclier.max
* [x] ge_ma_wea_trib_lance1m.max
* [x] ge_ma_wea_trib_lance2m.max
* [x] ge_tr_wea_trib_dague.max (140% scale?)
* [x] ge_tr_wea_trib_epee1m.max
* [x] ge_tr_wea_trib_epee2m.max
* [x] ge_tr_wea_trib_pistolarc.max (92,593% scale?)
* [x] ge_zo_wea_trib_baton.max
* [x] ge_zo_wea_trib_fusarc.max
* [x] ge_zo_wea_trib_masse1m.max
* [x] ge_zo_wea_trib_masse2m.max
