### ISSUE TITLE
Missing textures for particles in Fyros, maybe crickets?

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#15]
![screenshot_2019-11-17_015](https://user-images.githubusercontent.com/44550003/69011182-22019800-0968-11ea-88b0-02c73bf21846.jpg)

**Comment by kaetemi** [comment]
It should be in client log which is missing when using dev client

**Comment by kaetemi** [comment]
Can you turn on the effects debug overlay to show which environment effect is affected? Thanks!

**Comment by kaetemi** [comment]
Fy-BirdA.ps

**Comment by kaetemi** [comment]
`strings * | grep -o ".*\.ps" | tr '[:upper:]' '[:lower:]' | sort -u`

**Comment by kaetemi** [comment]
```
birda02.shape
birda03.shape
```

**Comment by kaetemi** [comment]
ctrl-alt-z

**Comment by kaetemi** [comment]
`WRN: Num vertices differs between meshs`

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/119604469-b08a8b80-be21-11eb-8e0a-b01ee3037179.png)
