### ISSUE TITLE
Ring UI bug cannot change creature aggro range

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#150]
![image](https://user-images.githubusercontent.com/69606701/93868817-eab7f200-fcc2-11ea-992b-3b9ef88c92e6.png)

Altering the value in game does not save.

Altering the Aggro value in r2_palette.lua and reloading,  does work and functions correctly on testing, issue is client based.

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/96937251-4c55c100-14fa-11eb-8c7a-14056e5c0780.png)

```
Exception will be launched: [string "       local editBox = getUICaller()    if ed..."]:1: 'then' expected near ';'
WRN: ELuaParseError: [string "       local editBox = getUICaller()    if ed..."]:1: 'then' expected near ';'
```

**Comment by kaetemi** [comment]
```
		prop = (char*) xmlGetProp( cur, (xmlChar*)"on_focus_lost" );
		if (prop) _AHOnFocusLost = (const char *) prop;
```

r2:buildEditBox -> strifyXml

**Comment by Xtarsia** [comment]
similar issue with "Minutes" and "Seconds" properties for both "Timed Spawner" and "Timer" components

![image](https://user-images.githubusercontent.com/69606701/97025384-e8f67e00-154f-11eb-993f-68fef4c526fb.png)
![image](https://user-images.githubusercontent.com/69606701/97025413-f3b11300-154f-11eb-8e94-1eb27917db25.png)

**Comment by kaetemi** [comment]
```
	local strxml = string.gsub(tostring(str), ">", "&gt;")
	strxml = string.gsub(strxml, "<", "&lt;")
	strxml = string.gsub(strxml, "&", "&amp;")
```
