### ISSUE TITLE
Component start up message checkbox does not save.

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#158]
![checkbox](https://user-images.githubusercontent.com/69606701/97043357-43043d00-156a-11eb-8ab2-104009d68e7c.png)

Unchecking and clicking ok > result should be not to see the window pop up again for that component.

actual > it shows every single time you place a new component.

**Comment by kaetemi** [comment]
Actually, the checkbox behaves in reverse.
