### ISSUE TITLE
$p tag not handled correctly in UI elements

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#170]
![image](https://user-images.githubusercontent.com/69606701/97623431-8dc7fe00-1a1d-11eb-8256-ba392dfcd735.png)

only 2 instances in the UI exist

workaround 
info_player.xml
`<group type="container" id="info_player_skills" w="500" title="uiSkillsTitle" global_color="false" header_color="UI:SAVE:WIN:COLORS:PLA"`

`<group type="container" id="info_player_skills" w="500" title="uihIdentity" global_color="false" header_color="UI:SAVE:WIN:COLORS:PLA"`

taskbar.xml
`<instance template="win_button" id="caracs"		color="UI:SAVE:WIN:COLORS:PLA" text="uimwProgression" posref="TL TL" x="0" y="-30 pushflag="UI:VARIABLES:ISACTIVE:CAREERS"	win_name="info_player_skills" />"`

`<instance template="win_button" id="caracs"		color="UI:SAVE:WIN:COLORS:PLA" text="uimwProgression2" posref="TL TL" x="0" y="-30 pushflag="UI:VARIABLES:ISACTIVE:CAREERS"	win_name="info_player_skills" />"`

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/97624736-71c55c00-1a1f-11eb-953e-8b75c20951ae.png)

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/97654743-9876a780-1a9e-11eb-8aa0-c57888495eba.png)
