### ISSUE TITLE
Bottom of list inventory is misaligned

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#182]
![image](https://user-images.githubusercontent.com/1581053/98168225-3b0eaa80-1f25-11eb-91c6-c466279fa897.png)

**Comment by kaetemi** [comment]
Also nudge the filter icons up a tick and the dapper field down a tick.

**Comment by Xtarsia** [comment]
add small space between search icon and other filters.

**Comment by Xtarsia** [comment]
Guild, Room and animal bags not at same alignment as bag. Fix aswell...

**Comment by Xtarsia** [comment]
increase minimum width slightly to prevent button overlap with "get" and "put" money buttons for guild inventory.

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/98481732-464b2a00-21f4-11eb-8d0f-d5ceb295dc62.png)
![image](https://user-images.githubusercontent.com/69606701/98481746-5d8a1780-21f4-11eb-9f2b-02b055fa8728.png)

pixel perfect
