### ISSUE TITLE
Weapon Texture in Preview window does not match displayed ingame Texture

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#201]
![screenshot_2020-11-14_000](https://user-images.githubusercontent.com/44550003/99144088-1a4ffe80-2663-11eb-8d06-585c45932709.jpg)

**Comment by kaetemi** [comment]
Texture is somehow specified by race

![image](https://user-images.githubusercontent.com/1581053/119729817-ad39e300-bea7-11eb-9d2e-c716c7126a45.png)

**Comment by kaetemi** [comment]
This is caused by the four textures ending with _fy, this being detected as a panoply texture, and the preview window incorrectly applying skin color to weapons.
