### ISSUE TITLE
Lakes ring map issues

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#212]
![Screenshot 2020-11-22 121148](https://user-images.githubusercontent.com/69606701/99903584-3be16380-2cbd-11eb-8bd6-bc7372b414bf.png)

Red dot = bad water (either missing, or no swimming and just run on the floor)
Blue dot = selectable in editor
Green dot = has a map when visited in game
Numbers = uiR2_eco##

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/99904358-550e0280-2d05-11eb-9313-837f4e653080.png)

**Comment by Xtarsia** [comment]
~~nothing pointed to that already, it could be added as 41. would need a name too.~~ Also, no map, not selectable, and water errors.

**Comment by Xtarsia** [comment]
uiR2_Lakes41    [GM Island (Sub Tropics )]

**Comment by Xtarsia** [comment]
Map 03 Water only present in southern part
![cap](https://user-images.githubusercontent.com/69606701/100467809-0ed0ee80-30cb-11eb-9c04-f81fbbf71278.png)

**Comment by Xtarsia** [comment]
map 04 Water visible, but missing. Walk on the floor only.
![image](https://user-images.githubusercontent.com/69606701/100468008-6c653b00-30cb-11eb-8b19-8c1d9173969d.png)

**Comment by Xtarsia** [comment]
Map 01 Water texture missing
![image](https://user-images.githubusercontent.com/69606701/100468291-0331f780-30cc-11eb-9771-91668936e896.png)

**Comment by Xtarsia** [comment]
Map 02 water texture missing, some alignment issues with water edges causing camera to jump to level with terrain whilst passing.

![image](https://user-images.githubusercontent.com/69606701/100468372-32e0ff80-30cc-11eb-80d9-0463525481f4.png)

**Comment by Xtarsia** [comment]
Map 09 Water only present in southern part

![cap](https://user-images.githubusercontent.com/69606701/100468579-9834f080-30cc-11eb-8ea5-238b82f1f15d.png)

**Comment by Xtarsia** [comment]
Map 10 Water only present in southern part

![cap](https://user-images.githubusercontent.com/69606701/100468729-e649f400-30cc-11eb-8a64-756827117ce5.png)

**Comment by Xtarsia** [comment]
a1 uiR2_Lakes01 uiR2EntryPoint01 /a Position 31346,-1310 N  Water not visible

l4 uiR2_Lakes02 uiR2EntryPoint01 /a Position 32059,-1392 N  Water not visible

l2 uiR2_Lakes03 uiR2EntryPoint01 /a Position 32961,-1388 N  Water not visible

~~l2 uiR2_Lakes08 uiR2EntryPoint01 /a Position 36991,-1311 E Water not visible~~

l3 uiR2_Lakes09 uiR2EntryPoint01 /a Position 37916,-1124 S  Water not visible

l2 uiR2_Lakes10 uiR2EntryPoint01 /a Position 38531,-1379 NE Water not visible

//z1 uiR2_Lakes13 uiR2EntryPoint /a Position 32880,-2080 S   entry point 01 needs adjusting & no map

l2 uiR2_Lakes16 uiR2EntryPoint01 /a Position 35330,-2120 W    Water not visible

l3 uiR2_Lakes21 uiR2EntryPoint01 /a Position 31247,-2790 E  no map

a1 uiR2_Lakes22 uiR2EntryPoint01 /a Position 32250,-2800 W  no map

l1 uiR2_Lakes27 uiR2EntryPoint01 /a Position 35605,-3080 NW water missing

l1 uiR2_Lakes39 uiR2EntryPoint01 /a Position 37510,-3900 N   no map

Lakes 41  /a Position 31487,-4904 is missing map has no entry points at all - missing from r2_entry_points.txt
