### ISSUE TITLE
Forest ring map issues

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#214]
![Screenshot 2020-11-22 162440](https://user-images.githubusercontent.com/69606701/99909267-57f5fc80-2cdf-11eb-8454-d9109a5ae8e6.png)

Red dot = bad water or bad terrain (either missing chunk, or no swimming and just run on the floor, or swimming in the air)
Blue dot = selectable in editor
Green dot = has a map when visited in game
Numbers = uiR2_eco##

**Comment by Xtarsia** [comment]
forest map 5 with a jungle tile? 
![image](https://user-images.githubusercontent.com/69606701/100384333-d91efd80-3017-11eb-9d9b-d012720b5c2d.png)

**Comment by Xtarsia** [comment]
all water is fixed

19 & 26 have possible tile issue

missing maps unchanged

**Comment by kaetemi** [comment]
Forest 22, 25 missing in wmap
Forest 40 missing some tiles in wmap (maybe a water issue)
