### ISSUE TITLE
R2 Forest 23 has a jungle tile

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#230]

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/103935834-f5d24900-511e-11eb-966e-261d1e2b7bc3.png)

**Comment by Xtarsia** [comment]
fixed 
![image](https://user-images.githubusercontent.com/69606701/104039213-ff66ba00-51cd-11eb-82ec-e1806a4911e9.png)
