### ISSUE TITLE
R2 Forest 19 water/heightmap issue

### ISSUE THREAD

**Issue by Xtarsia** [kaetemi/ryzomclassic#232]
25162,-11919
![image](https://user-images.githubusercontent.com/69606701/103933779-d4bc2900-511b-11eb-8b0b-aef2f81d27aa.png)

**Comment by Xtarsia** [comment]
also has a jungle tile

![image](https://user-images.githubusercontent.com/69606701/103936477-5eb9c100-511f-11eb-8a9f-71d069436d6b.png)

**Comment by kaetemi** [comment]
Jungle tile replaced.
Height map not yet addressed.

**Comment by Xtarsia** [comment]
tile fixed
![image](https://user-images.githubusercontent.com/69606701/104039628-86b42d80-51ce-11eb-9c5b-5e002b487072.png)

**Comment by kaetemi** [comment]
https://github.com/kaetemi/ryzomclassic/issues/234
Address with alpha maps
