### ISSUE TITLE
Amber glow on Zora buildings not sized correctly

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#53]
![image](https://user-images.githubusercontent.com/1581053/69465569-71a6f000-0dbc-11ea-9ca7-a79dd9d9d6ee.png)

**Comment by mlcdev** [comment]
Confirmed
![screenshot_2019-11-24_005](https://user-images.githubusercontent.com/44550003/69498356-6b616280-0ee7-11ea-9128-0fde5999a134.jpg)

**Comment by ryzom-pipeline** [comment]
See https://github.com/ryzom/ryzomcore/issues/336

**Comment by kaetemi** [comment]
kaetemi@athena:/mnt/x/wsl$ egrep 'FirstFlareKeepSize' --include *.max -r /mnt/y/ryzomclassic/graphics/
Binary file /mnt/y/ryzomclassic/graphics/landscape/ligo/desert/max/zonematerial-converted-165_eg.max matches
Binary file /mnt/y/ryzomclassic/graphics/landscape/ligo/jungle/max/zonematerial-foret-appart.max matches
Binary file /mnt/y/ryzomclassic/graphics/landscape/ligo/jungle/max/zonematerial-foret-start_village_newbieland.max matches
Binary file /mnt/y/ryzomclassic/graphics/sfx/meshtoparticle/flare_preoder_item.max matches
Binary file /mnt/y/ryzomclassic/graphics/sky_v2/max/de_sky_dome.max matches
Binary file /mnt/y/ryzomclassic/graphics/sky_v2/max/fo_sky_dome.max matches
Binary file /mnt/y/ryzomclassic/graphics/sky_v2/max/ju_sky_dome.max matches
Binary file /mnt/y/ryzomclassic/graphics/sky_v2/max/la_sky_dome.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/generique/decors/constructions/autel_kami/gen_bt_autel_kami.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/generique/decors/constructions/gen_bt_autel_kami.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/generique/decors/constructions/gen_bt_comptoir.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/agora/zo_bt_agora.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/appart_joueur/zo_bt_appart.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/autel_kamique/zo_bt_autel.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/bar/zo_bt_bar.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/hall_conseil/zo_bt_hall_conseil.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/hall_reunion_vitrine/zo_bt_hall_reunion_vitrine.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/mairie/zo_cn_mairie.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/mobiliers/zo_table.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/module mairie/zo_bt_module_mairie.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/monastere/zo_bt_monastere.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/work/mairie-soussol.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/zo_bt_monastere.max matches
Binary file /mnt/y/ryzomclassic/graphics/stuff/zorai/decors/constructions/zo_cn_mairie.max matches
