### ISSUE TITLE
Rbank build uses NH zone as reference, but welded zones don't match

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#58]
Rbank builder takes non-heightmapped zone to ensure heightmap doesn't affect collisions.

> "ERROR: The zone %s has a different bind strucutre in the landscape and in the landscape_with_No_Heightmap"

Adjust zone welder to weld two versions at the same time.

**Comment by mlcdev** [comment]
Also typo in the error message "has a different bind **strucutre** "
