### ISSUE TITLE
map on zorai starter island is distorted

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#59]
![screenshot_2019-11-23_000](https://user-images.githubusercontent.com/44550003/69475924-6e6b2e80-0dd3-11ea-9e3b-d48e9fb52cc1.jpg)

**Comment by mlcdev** [comment]
Also assets are broken. Floaty stuff.

**Comment by Xtarsia** [comment]
![image](https://user-images.githubusercontent.com/69606701/90322539-795f8380-df4d-11ea-8359-674d17ddbed2.png)
![image](https://user-images.githubusercontent.com/69606701/90322552-93996180-df4d-11ea-8da2-5f8c6f84664c.png)

City level maps are not clickable (cursor is hovering over Pyr)

Clicking the back arrow at the top left to get to the world map result in a blank screen with no simple way to get back to the region map.

**Comment by kaetemi** [comment]
- [x] Add script to sneak classic textures (map and splash screens) into the build, since they're not in the source graphics

**Comment by kaetemi** [comment]
![image](https://user-images.githubusercontent.com/1581053/99881705-300e8680-2c56-11eb-890a-277861a4f180.png)
