### ISSUE TITLE
No generic magic amplifier available on Zorai newbieland

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#64]
There's no generic magic amplifier available on Zorai newbieland. The first Acid upgrade already requires a new amplifier.

This impacts progress of magic users compared to melee users.

Range weapons don't seem available either.

Was this restriction imposed with Silan?

**Comment by kaetemi** [comment]
Giving a generic amp to players and not having it on the merchants is odd.

**Comment by mlcdev** [comment]
Silan had no range weapons and amps were handed out as quest rewards. Imho no generic NPC amps available.

**Comment by kaetemi** [comment]
So how about the original starter islands?

**Comment by kaetemi** [comment]
In beta they had the old newbie armor in all colors at the merchants on
newbie land.

>

**Comment by kaetemi** [comment]
According to https://forums.ryzom.com/archive/index.php/t-16142.html this was the case originally as well, no amplifier being available for sale on newbie island.

**Comment by kaetemi** [comment]
There's no amps available on Hawkers either, are there?
