### ISSUE TITLE
client stuck returning from launched ring scenario

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#83]
Log on the normal shard and launch a scenario from the terminal with default settings. Then quit the scenario, client is stuck in loading screen. Log attached.

2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 129
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 130
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 131
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 132
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 133
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 134
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 135
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 136
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe editor.cpp 6562 R2::CEditor::removeInstanceObserver : removeInstanceObserver : Instance observer handle not found : 137
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_gateway.cpp 1658 NLNET::CStandardGateway::onModuleUnplugged : NETL6: Gateway clientGw : unplugging module 'ClientEditionModule' id=2
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_manager.cpp 651 NLNET::CModuleManager::releaseModuleProxy : Releasing module proxy ('vision:72:ClientEditionModule', ID : 3)
2020/03/29 23:29:09 INF 2088 ryzom_client_dev_r.exe command.cpp 182 NLMISC::CCommandRegistry::unregisterNamedCommandHandler : CCommandRegistry : removing commands handler for class 'CModuleBase'
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_gateway.cpp 384 NLNET::CStandardGateway::deleteTransport : NETL6: Gateway transport 'fec' deleted
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_gateway.cpp 1775 NLNET::CStandardGateway::removeForeignModule : Gateway 'clientGw' : removing foreign module info for 'wiksie:26149:ServerAnimationModule'
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_manager.cpp 651 NLNET::CModuleManager::releaseModuleProxy : Releasing module proxy ('wiksie:26149:ServerAnimationModule', ID : 5)
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_gateway.cpp 1775 NLNET::CStandardGateway::removeForeignModule : Gateway 'clientGw' : removing foreign module info for 'wiksie:26149:ServerEditionModule'
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_manager.cpp 651 NLNET::CModuleManager::releaseModuleProxy : Releasing module proxy ('wiksie:26149:ServerEditionModule', ID : 4)
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_manager.cpp 556 NLNET::CModuleManager::unregisterModuleSocket : Unregistering module socket 'clientGw'
2020/03/29 23:29:09 DBG 2088 ryzom_client_dev_r.exe module_manager.cpp 591 NLNET::CModuleManager::unregisterModuleGateway : Unregistering module gateway 'clientGw'
2020/03/29 23:29:09 INF 2088 ryzom_client_dev_r.exe command.cpp 182 NLMISC::CCommandRegistry::unregisterNamedCommandHandler : CCommandRegistry : removing commands handler for class 'CStandardGateway'
2020/03/29 23:29:09 WRN 2088 ryzom_client_dev_r.exe co_task.cpp 153 NLMISC::TCoTaskData::startFunc : CCoTask::startFunc : the task has generated an unhandled exeption and will terminate
2020/03/29 23:29:10 DBG 164c ryzom_client_dev_r.exe session_browser.cpp 268 CSessionBrowser::run : SB: Disconnecting

**Comment by mlcdev** [comment]
Attached the scenario which caused the behaviour.

[Atys in Trouble.zip](https://github.com/kaetemi/ryzomclassic/files/4399839/Atys.in.Trouble.zip)

**Comment by kaetemi** [comment]
> it is on my left side of the screen the big stop scenario button of the 3 ring things
> kick all players and stop scenario

**Comment by mlcdev** [comment]
Visualized steps to recreate...

![screenshot_2020-03-29_000](https://user-images.githubusercontent.com/44550003/77861897-33ad5300-7218-11ea-8663-5ad5be81320f.jpg)

![screenshot_2020-03-29_001](https://user-images.githubusercontent.com/44550003/77861903-3a3bca80-7218-11ea-82f2-392cb61fba43.jpg)

**Comment by kaetemi** [comment]
```
 	ryzom_client_dev_d.exe!NLMISC::getCallStack(std::string & result, int skipNFirst) Line 1031	C++
 	ryzom_client_dev_d.exe!NLMISC::getCallStackAndLog(std::string & result, int skipNFirst) Line 1089	C++
 	ryzom_client_dev_d.exe!NLMISC::CLog::displayString(const char * str) Line 309	C++
 	ryzom_client_dev_d.exe!NLMISC::CLog::_displayNL(const char * format, ...) Line 345	C++
 	ryzom_client_dev_d.exe!NLMISC::_assertex_stop_0(bool & ignoreNextTime, int line, const char * file, const char * funcName, const char * exp) Line 283	C++
 	ryzom_client_dev_d.exe!NLMISC::_assert_stop(bool & ignoreNextTime, int line, const char * file, const char * funcName, const char * exp) Line 297	C++
>	ryzom_client_dev_d.exe!CInventoryManager::updateItemInfoQueue() Line 3592	C++
 	ryzom_client_dev_d.exe!CInventoryManager::onReceiveItemSheet(NLMISC::ICDBNode * node) Line 3542	C++
 	ryzom_client_dev_d.exe!CInventoryManager::CItemSheetObs::update(NLMISC::ICDBNode * node) Line 3486	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeLeaf::notifyObservers() Line 372	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeLeaf::setValue64(__int64 prop) Line 304	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeLeaf::resetData(unsigned int gc, bool forceReset) Line 199	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeBranch::resetData(unsigned int gc, bool forceReset) Line 157	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeBranch::resetData(unsigned int gc, bool forceReset) Line 157	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeBranch::resetData(unsigned int gc, bool forceReset) Line 157	C++
 	ryzom_client_dev_d.exe!NLMISC::CCDBNodeBranch::resetData(unsigned int gc, bool forceReset) Line 157	C++
 	ryzom_client_dev_d.exe!CNetworkConnection::reinit() Line 2972	C++
 	ryzom_client_dev_d.exe!CNetManager::reinit() Line 4096	C++
 	ryzom_client_dev_d.exe!CFarTP::disconnectFromPreviousShard() Line 1180	C++
 	ryzom_client_dev_d.exe!CLoginStateMachine::run() Line 617	C++
 	ryzom_client_dev_d.exe!NLMISC::TCoTaskData::startFunc(void * param) Line 149	C++
 	[External Code]	

```
