### ISSUE TITLE
Ring stuck in message loop on loading

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#89]
Go to terminal and try to load.

[f2p_atys.ZIP](https://github.com/kaetemi/ryzomclassic/files/4414195/f2p_atys.ZIP)

**Comment by kaetemi** [comment]
You can hit ALT+F4 and hammer Character Selection to get out of the loop.

**Comment by kaetemi** [comment]
I'm guessing the landscape is missing for this one.
